# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list   
# 20230708
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/abshare/abshare.github.io/main/README.md

- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/mksshare/mksshare.github.io/main/README.md

- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/WilliamStar007/ClashX-V2Ray-TopFreeProxy/main/README.md

- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list_raw.txt

- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/yaney01/Yaney01/main/README.md

# 20230729
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/HakurouKen/free-node/main/public

# 20230813
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/actives.txt

# 20230909
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt

# 20231108
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt

# 20240218
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/markbang/chromegopacs/main/hy2pac.txt

# 20240415
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/imohammadkhalili/V2RAY/main/Mkhalili

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
